# Generated by Django 3.0.7 on 2020-09-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('localisation', models.CharField(max_length=255, verbose_name='lieu')),
                ('commission_date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('alerted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom et prénoms')),
                ('victim_residence', models.CharField(max_length=255)),
                ('abuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_abuse', to='api.Abus')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom et prénoms')),
                ('author_residence', models.CharField(max_length=255)),
                ('abuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_abuse', to='api.Abus')),
            ],
        ),
        migrations.CreateModel(
            name='Alerter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonyme', max_length=255, verbose_name='Nom et prénoms')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Téléphone')),
                ('residence', models.CharField(blank=True, max_length=255, null=True)),
                ('abuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerter_abuse', to='api.Abus')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_abuse', to='api.Abus')),
            ],
        ),
    ]
